import pytest
from unittest.mock import patch, MagicMock
from legal_advisory import get_legal_advisory, _haversine_distance

# -----------------------------------------------------------------------------
# Mock Data
# -----------------------------------------------------------------------------
MOCK_SOURCES = [
    {
        "id": "s1",
        "name": "Badarpur Power Plant",
        "type": "thermal_plant",
        "lat": 28.5033,
        "lng": 77.3040
    },
    {
        "id": "s2",
        "name": "Okhla Industrial Area",
        "type": "industrial",
        "lat": 28.5273,
        "lng": 77.2798
    },
    {
        "id": "s3",
        "name": "Central Metro Construction",
        "type": "construction",
        "lat": 28.6143,
        "lng": 77.2118
    },
    {
        "id": "s4",
        "name": "Ashram Chowk Traffic",
        "type": "traffic_corridor",
        "lat": 28.5721,
        "lng": 77.2570
    },
    {
        "id": "s5",
        "name": "Noida Illegal Sector",
        "type": "unknown_type",
        "lat": 28.6000,
        "lng": 77.3000
    }
]

class MockGeminiResponse:
    def __init__(self, text):
        self.text = text


# -----------------------------------------------------------------------------
# Tests Setup & Happy Path
# -----------------------------------------------------------------------------

@patch("legal_advisory.client")
@patch("legal_advisory.get_table")
@patch("legal_advisory.get_violation_history")
def test_successful_advisory_generation(mock_violation_history, mock_get_table, mock_client):
    """
    1. Successful advisory generation.
    Validates that when database queries and Gemini calls succeed, all required
    keys are present and narratives are retrieved from the AI model.
    """
    mock_get_table.return_value = MOCK_SOURCES
    mock_violation_history.return_value = {"total_notices": 0}
    
    # Mock Gemini JSON response
    mock_client.models.generate_content.return_value = MockGeminiResponse(
        '{"citizen_rights_text": "Rights generated by AI.", "complaint_guidance_text": "Guidance generated by AI."}'
    )
    
    result = get_legal_advisory(lat=28.5033, lng=77.3040, source_id="s1")
    
    assert result["citizen_rights_text"] == "Rights generated by AI."
    assert result["complaint_guidance_text"] == "Guidance generated by AI."
    assert "notice_status" in result
    assert "relevant_authority" in result


# -----------------------------------------------------------------------------
# Regulatory Authority Mapping Tests
# -----------------------------------------------------------------------------

@patch("legal_advisory.client", None)  # Bypass AI to test python logic
@patch("legal_advisory.get_table")
def test_authority_thermal_plant(mock_get_table):
    """
    2. Known thermal plant source.
    Asserts source mapping 'thermal_plant' -> 'Central Pollution Control Board (CPCB)'.
    """
    mock_get_table.return_value = MOCK_SOURCES
    result = get_legal_advisory(lat=28.5033, lng=77.3040, source_id="s1")
    assert result["relevant_authority"] == "Central Pollution Control Board (CPCB)"


@patch("legal_advisory.client", None)
@patch("legal_advisory.get_table")
def test_authority_industrial(mock_get_table):
    """
    3. Known industrial source.
    Asserts source mapping 'industrial' -> 'State Pollution Control Board (SPCB)'.
    """
    mock_get_table.return_value = MOCK_SOURCES
    result = get_legal_advisory(lat=28.5273, lng=77.2798, source_id="s2")
    assert result["relevant_authority"] == "State Pollution Control Board (SPCB)"


@patch("legal_advisory.client", None)
@patch("legal_advisory.get_table")
def test_authority_construction(mock_get_table):
    """
    4. Known construction source.
    Asserts source mapping 'construction' -> 'Municipal Corporation / Local Authority'.
    """
    mock_get_table.return_value = MOCK_SOURCES
    result = get_legal_advisory(lat=28.6143, lng=77.2118, source_id="s3")
    assert result["relevant_authority"] == "Municipal Corporation / Local Authority"


@patch("legal_advisory.client", None)
@patch("legal_advisory.get_table")
def test_authority_traffic_corridor(mock_get_table):
    """
    5. Known traffic corridor source.
    Asserts source mapping 'traffic_corridor' -> 'Traffic Police and Municipal Authority'.
    """
    mock_get_table.return_value = MOCK_SOURCES
    result = get_legal_advisory(lat=28.5721, lng=77.2570, source_id="s4")
    assert result["relevant_authority"] == "Traffic Police and Municipal Authority"


@patch("legal_advisory.client", None)
@patch("legal_advisory.get_table")
def test_authority_unknown_type(mock_get_table):
    """
    6. Unknown source type.
    Asserts unknown source maps to fallback 'Local Pollution Control Authority'.
    """
    mock_get_table.return_value = MOCK_SOURCES
    result = get_legal_advisory(lat=28.6000, lng=77.3000, source_id="s5")
    assert result["relevant_authority"] == "Local Pollution Control Authority"


# -----------------------------------------------------------------------------
# Notice Status Tests
# -----------------------------------------------------------------------------

@patch("legal_advisory.client", None)
@patch("legal_advisory.get_table")
@patch("legal_advisory.get_violation_history")
def test_notice_status_previous_notices(mock_violation_history, mock_get_table):
    """
    7. Source with previous notices.
    Asserts status maps correctly when notices exist.
    """
    mock_get_table.return_value = MOCK_SOURCES
    mock_violation_history.return_value = {"total_notices": 3}
    
    result = get_legal_advisory(lat=28.5000, lng=77.3000, source_id="s1")
    assert result["notice_status"] == "Official notices have previously been issued against this source."


@patch("legal_advisory.client", None)
@patch("legal_advisory.get_table")
@patch("legal_advisory.get_violation_history")
def test_notice_status_no_previous_notices(mock_violation_history, mock_get_table):
    """
    8. Source with no notices.
    Asserts status maps correctly when notices array is empty.
    """
    mock_get_table.return_value = MOCK_SOURCES
    mock_violation_history.return_value = {"total_notices": 0}
    
    result = get_legal_advisory(lat=28.5000, lng=77.3000, source_id="s1")
    assert result["notice_status"] == "No previous notices have been recorded."


@patch("legal_advisory.client", None)
@patch("legal_advisory.get_table")
def test_notice_status_no_source_id(mock_get_table):
    """
    9. No source_id supplied.
    Asserts notice status is 'Unknown'.
    Assures spatial lookup locates nearby Okhla (s2) when coordinates are close.
    """
    mock_get_table.return_value = MOCK_SOURCES
    
    # Query close to Okhla (28.5273, 77.2798)
    result = get_legal_advisory(lat=28.5270, lng=77.2790, source_id=None)
    
    assert result["notice_status"] == "Unknown"
    assert result["relevant_authority"] == "State Pollution Control Board (SPCB)"


# -----------------------------------------------------------------------------
# Failures & Boundaries Error Handling Tests
# -----------------------------------------------------------------------------

@patch("legal_advisory.client")
@patch("legal_advisory.get_table")
def test_gemini_failure_graceful_fallback(mock_get_table, mock_client):
    """
    10. Gemini failure.
    Raises exception from mocked Gemini client.
    Verifies that the function does not crash and falls back to pre-written guidelines.
    """
    mock_get_table.return_value = MOCK_SOURCES
    mock_client.models.generate_content.side_effect = Exception("API rate limit exceeded")
    
    result = get_legal_advisory(lat=28.5033, lng=77.3040, source_id="s1")
    
    assert "Under the Air (Prevention and Control of Pollution) Act" in result["citizen_rights_text"]
    assert "CPCB SAMEER" in result["complaint_guidance_text"]


@patch("legal_advisory.get_table")
@patch("legal_advisory.get_violation_history")
def test_database_failure_graceful_fallback(mock_violation_history, mock_get_table):
    """
    11. Database failure.
    Raises exception from database queries.
    Asserts that default status ('Unknown') and fallback authority are used.
    """
    mock_get_table.side_effect = Exception("Supabase connection timed out")
    mock_violation_history.side_effect = Exception("Supabase connection timed out")
    
    result = get_legal_advisory(lat=28.5033, lng=77.3040, source_id="s1")
    
    assert result["notice_status"] == "No previous notices have been recorded."
    assert result["relevant_authority"] == "Local Pollution Control Authority"


@patch("legal_advisory.client", None)
@patch("legal_advisory.get_table")
def test_invalid_coordinates_safety(mock_get_table):
    """
    12. Invalid coordinates.
    Passes string coordinate structures to get_legal_advisory.
    Function should intercept TypeErrors and fail gracefully.
    """
    mock_get_table.return_value = MOCK_SOURCES
    
    # Must run without throwing unhandled exceptions
    result = get_legal_advisory(lat="invalid", lng="invalid", source_id=None)
    
    assert result["relevant_authority"] == "Local Pollution Control Authority"


@patch("legal_advisory.client", None)
@patch("legal_advisory.get_table")
def test_missing_source_record_fallback(mock_get_table):
    """
    13. Missing source record.
    Supplies source_id not present in sources.
    Asserts fallback authority and default notice status are applied.
    """
    mock_get_table.return_value = MOCK_SOURCES
    
    result = get_legal_advisory(lat=28.5, lng=77.3, source_id="s_missing")
    
    assert result["relevant_authority"] == "Local Pollution Control Authority"
    assert result["notice_status"] == "No previous notices have been recorded."


# -----------------------------------------------------------------------------
# Output Payload Structural Checks
# -----------------------------------------------------------------------------

@patch("legal_advisory.client", None)
@patch("legal_advisory.get_table")
def test_output_structure_keys(mock_get_table):
    """
    14. Output structure.
    Checks that the returned dictionary matches the spec schema EXACTLY.
    """
    mock_get_table.return_value = MOCK_SOURCES
    result = get_legal_advisory(lat=28.5, lng=77.3, source_id="s1")
    
    expected_keys = {
        "citizen_rights_text",
        "complaint_guidance_text",
        "notice_status",
        "relevant_authority"
    }
    assert set(result.keys()) == expected_keys


@patch("legal_advisory.client", None)
@patch("legal_advisory.get_table")
def test_output_values_are_strings(mock_get_table):
    """
    15. Verify all returned values are strings.
    Validates data types of the values returned in the dictionary.
    """
    mock_get_table.return_value = MOCK_SOURCES
    result = get_legal_advisory(lat=28.5, lng=77.3, source_id="s1")
    
    for key, val in result.items():
        assert isinstance(val, str), f"Key {key} has non-string value: {type(val)}"
